/**
 * @fileoverview Pre-transpile `src/web-sanitize.ts` into a browser-ready JS
 *               text file so `web.ts` can text-import it.
 *
 * Why: Bun's `with { type: "text" }` import attribute does NOT override
 * Bun's built-in TypeScript module loader. Importing a `.ts` file with the
 * text attribute fails at runtime with `Missing 'default' export` because
 * Bun parses it as a TS module first. The workaround is to ship the source
 * to a file with an extension Bun's text import accepts (`.js`, `.txt`,
 * `.md`, etc.). Running Bun.Transpiler ahead of time also removes the
 * runtime transpile step that previously happened on every fresh process.
 *
 * Output: `src/web-sanitize.embed.js`. Gitignored — regenerated by the
 * `prepare`, `pretest`, and `prebuild:bin` npm lifecycle hooks so devs and
 * CI never see stale content. If you modify `web-sanitize.ts`, run
 * `npm run embed:web-sanitize` (or any of the hook-bearing commands) before
 * exercising the web UI.
 *
 * Cross-references:
 *   - src/web-sanitize.ts — the source of truth
 *   - src/web.ts — text-imports the generated file
 *   - .gitignore — the output is intentionally not checked in
 */

import { dirname, join, resolve } from "node:path";

const REPO_ROOT = resolve(dirname(import.meta.dir));
const SRC = join(REPO_ROOT, "src", "web-sanitize.ts");
const OUT = join(REPO_ROOT, "src", "web-sanitize.embed.js");

const source = await Bun.file(SRC).text();
const transpiler = new Bun.Transpiler({ loader: "ts", target: "browser" });
const transpiled = transpiler.transformSync(source);

const banner =
  "// AUTOGENERATED by scripts/embed-web-sanitize.ts. DO NOT EDIT.\n" +
  "// Source: src/web-sanitize.ts. Regenerate via `npm run embed:web-sanitize`.\n";

await Bun.write(OUT, banner + transpiled);
console.log(`embed:web-sanitize → ${OUT} (${transpiled.length} bytes)`);
